/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyAddNews {
        "body": string;
        "title": string;
    }
    interface MyHome {
    }
    interface MyNavbar {
    }
    interface MyNews {
    }
    interface MyNewsPage {
        "news": any;
        "page": string;
    }
    interface MyRouter {
    }
}
declare global {
    interface HTMLMyAddNewsElement extends Components.MyAddNews, HTMLStencilElement {
    }
    var HTMLMyAddNewsElement: {
        prototype: HTMLMyAddNewsElement;
        new (): HTMLMyAddNewsElement;
    };
    interface HTMLMyHomeElement extends Components.MyHome, HTMLStencilElement {
    }
    var HTMLMyHomeElement: {
        prototype: HTMLMyHomeElement;
        new (): HTMLMyHomeElement;
    };
    interface HTMLMyNavbarElement extends Components.MyNavbar, HTMLStencilElement {
    }
    var HTMLMyNavbarElement: {
        prototype: HTMLMyNavbarElement;
        new (): HTMLMyNavbarElement;
    };
    interface HTMLMyNewsElement extends Components.MyNews, HTMLStencilElement {
    }
    var HTMLMyNewsElement: {
        prototype: HTMLMyNewsElement;
        new (): HTMLMyNewsElement;
    };
    interface HTMLMyNewsPageElement extends Components.MyNewsPage, HTMLStencilElement {
    }
    var HTMLMyNewsPageElement: {
        prototype: HTMLMyNewsPageElement;
        new (): HTMLMyNewsPageElement;
    };
    interface HTMLMyRouterElement extends Components.MyRouter, HTMLStencilElement {
    }
    var HTMLMyRouterElement: {
        prototype: HTMLMyRouterElement;
        new (): HTMLMyRouterElement;
    };
    interface HTMLElementTagNameMap {
        "my-add-news": HTMLMyAddNewsElement;
        "my-home": HTMLMyHomeElement;
        "my-navbar": HTMLMyNavbarElement;
        "my-news": HTMLMyNewsElement;
        "my-news-page": HTMLMyNewsPageElement;
        "my-router": HTMLMyRouterElement;
    }
}
declare namespace LocalJSX {
    interface MyAddNews {
        "body"?: string;
        "onNewsAdded"?: (event: CustomEvent<any>) => void;
        "title"?: string;
    }
    interface MyHome {
    }
    interface MyNavbar {
    }
    interface MyNews {
    }
    interface MyNewsPage {
        "news"?: any;
        "onNewsDeleted"?: (event: CustomEvent<any>) => void;
        "page"?: string;
    }
    interface MyRouter {
    }
    interface IntrinsicElements {
        "my-add-news": MyAddNews;
        "my-home": MyHome;
        "my-navbar": MyNavbar;
        "my-news": MyNews;
        "my-news-page": MyNewsPage;
        "my-router": MyRouter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-add-news": LocalJSX.MyAddNews & JSXBase.HTMLAttributes<HTMLMyAddNewsElement>;
            "my-home": LocalJSX.MyHome & JSXBase.HTMLAttributes<HTMLMyHomeElement>;
            "my-navbar": LocalJSX.MyNavbar & JSXBase.HTMLAttributes<HTMLMyNavbarElement>;
            "my-news": LocalJSX.MyNews & JSXBase.HTMLAttributes<HTMLMyNewsElement>;
            "my-news-page": LocalJSX.MyNewsPage & JSXBase.HTMLAttributes<HTMLMyNewsPageElement>;
            "my-router": LocalJSX.MyRouter & JSXBase.HTMLAttributes<HTMLMyRouterElement>;
        }
    }
}
