/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TabActivateEvent } from "./components/my-tabs/my-tab";
export namespace Components {
    interface MyAddNews {
        "body": string;
        "title": string;
    }
    interface MyComponent {
        "kind": "info" | "success" | "error";
        "text": string;
    }
    interface MyNews {
        "newsList": any;
    }
    interface MyNewsPage {
        "news": any;
    }
    interface MyRouter {
    }
    interface MyTab {
        "active": boolean;
        "name": string;
    }
    interface MyTabs {
        "activeTab": string;
    }
}
declare global {
    interface HTMLMyAddNewsElement extends Components.MyAddNews, HTMLStencilElement {
    }
    var HTMLMyAddNewsElement: {
        prototype: HTMLMyAddNewsElement;
        new (): HTMLMyAddNewsElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyNewsElement extends Components.MyNews, HTMLStencilElement {
    }
    var HTMLMyNewsElement: {
        prototype: HTMLMyNewsElement;
        new (): HTMLMyNewsElement;
    };
    interface HTMLMyNewsPageElement extends Components.MyNewsPage, HTMLStencilElement {
    }
    var HTMLMyNewsPageElement: {
        prototype: HTMLMyNewsPageElement;
        new (): HTMLMyNewsPageElement;
    };
    interface HTMLMyRouterElement extends Components.MyRouter, HTMLStencilElement {
    }
    var HTMLMyRouterElement: {
        prototype: HTMLMyRouterElement;
        new (): HTMLMyRouterElement;
    };
    interface HTMLMyTabElement extends Components.MyTab, HTMLStencilElement {
    }
    var HTMLMyTabElement: {
        prototype: HTMLMyTabElement;
        new (): HTMLMyTabElement;
    };
    interface HTMLMyTabsElement extends Components.MyTabs, HTMLStencilElement {
    }
    var HTMLMyTabsElement: {
        prototype: HTMLMyTabsElement;
        new (): HTMLMyTabsElement;
    };
    interface HTMLElementTagNameMap {
        "my-add-news": HTMLMyAddNewsElement;
        "my-component": HTMLMyComponentElement;
        "my-news": HTMLMyNewsElement;
        "my-news-page": HTMLMyNewsPageElement;
        "my-router": HTMLMyRouterElement;
        "my-tab": HTMLMyTabElement;
        "my-tabs": HTMLMyTabsElement;
    }
}
declare namespace LocalJSX {
    interface MyAddNews {
        "body"?: string;
        "onNewsAdded"?: (event: CustomEvent<any>) => void;
        "title"?: string;
    }
    interface MyComponent {
        "kind"?: "info" | "success" | "error";
        "onAcknowledge"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface MyNews {
        "newsList"?: any;
    }
    interface MyNewsPage {
        "news"?: any;
        "onNewsDeleted"?: (event: CustomEvent<any>) => void;
    }
    interface MyRouter {
    }
    interface MyTab {
        "active"?: boolean;
        "name"?: string;
        "onTabActivate"?: (event: CustomEvent<TabActivateEvent>) => void;
    }
    interface MyTabs {
        "activeTab"?: string;
    }
    interface IntrinsicElements {
        "my-add-news": MyAddNews;
        "my-component": MyComponent;
        "my-news": MyNews;
        "my-news-page": MyNewsPage;
        "my-router": MyRouter;
        "my-tab": MyTab;
        "my-tabs": MyTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-add-news": LocalJSX.MyAddNews & JSXBase.HTMLAttributes<HTMLMyAddNewsElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-news": LocalJSX.MyNews & JSXBase.HTMLAttributes<HTMLMyNewsElement>;
            "my-news-page": LocalJSX.MyNewsPage & JSXBase.HTMLAttributes<HTMLMyNewsPageElement>;
            "my-router": LocalJSX.MyRouter & JSXBase.HTMLAttributes<HTMLMyRouterElement>;
            "my-tab": LocalJSX.MyTab & JSXBase.HTMLAttributes<HTMLMyTabElement>;
            "my-tabs": LocalJSX.MyTabs & JSXBase.HTMLAttributes<HTMLMyTabsElement>;
        }
    }
}
